maintainer       "Best Buy"
maintainer_email "bryan.brandau@bestbuy.com"
license          "All rights reserved"
description      "Installs/Configures Splunk Server, Forwarder, Deployment Monitor and *nix App"
version          "0.0.2"
